plugins {
    id 'java'
    id 'io.qameta.allure' version '2.12.0'
}

group = 'com.mohammad'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testImplementation 'io.qameta.allure:allure-junit5:2.29.1'
    implementation('org.slf4j:slf4j-api:2.0.12')
    implementation('ch.qos.logback:logback-classic:1.5.13')
}

test {
    useJUnitPlatform()
}